"""
Customer-facing AI support assistant for the storefront chat widget.

Works out of the box with no API key: a fast, inventory-aware rule engine
answers the common questions (availability, price, financing, test drives,
opening hours, location). If ANTHROPIC_API_KEY is set in the environment,
answers are instead generated by Claude with the live inventory and the
rule-engine facts passed in as context, so responses stay grounded in real
stock and never invent a car that doesn't exist.
"""
import os
import re

BUSINESS_NAME = os.environ.get("BUSINESS_NAME", "AutoLot237")
BUSINESS_HOURS = os.environ.get("BUSINESS_HOURS", "Mon–Sat, 8:00–18:00 (WAT)")
BUSINESS_LOCATION = os.environ.get("BUSINESS_ADDRESS", "Bonanjo, Douala, Cameroon")
WHATSAPP_NUMBER = os.environ.get("WHATSAPP_NUMBER", "")

GREETINGS = ("hi", "hello", "hey", "good morning", "good afternoon", "good evening", "bonjour")


def _matching_cars(message, limit=4):
    from app.models.car import CarListing
    from app.models.product import Product

    q = CarListing.query.join(Product).filter(
        CarListing.is_published.is_(True),
        Product.is_active.is_(True),
        Product.stock_quantity > 0,
    )

    words = re.findall(r"[a-zA-Z]+", message.lower())
    makes = {"toyota", "honda", "hyundai", "kia", "nissan", "ford", "mercedes",
             "bmw", "lexus", "peugeot", "suzuki", "mazda", "volkswagen", "audi"}
    hit_makes = [w for w in words if w in makes]

    if hit_makes:
        q = q.filter(CarListing.make.ilike(f"%{hit_makes[0]}%"))

    price_match = re.search(r"(\d[\d,\.]{3,})", message.replace(",", ""))
    budget = None
    if "under" in message.lower() or "below" in message.lower() or "less than" in message.lower():
        if price_match:
            try:
                budget = float(price_match.group(1))
                q = q.join(Product, CarListing.product_id == Product.id) if False else q
            except ValueError:
                budget = None

    results = q.order_by(CarListing.created_at.desc()).limit(30).all()
    if budget:
        results = [c for c in results if c.price <= budget]
    return results[:limit]


def _format_cars(cars):
    if not cars:
        return None
    lines = []
    for c in cars:
        lines.append(f"• {c.title} — {c.mileage_km:,} km, {c.transmission}, {c.price:,.0f} {os.environ.get('CURRENCY_SYMBOL', 'CFA')} ({c.listing_code})")
    return "\n".join(lines)


def _rule_based_reply(message, session_history=None):
    text = message.lower().strip()

    if any(text.startswith(g) or text == g for g in GREETINGS):
        return (f"Hi! I'm the {BUSINESS_NAME} assistant. I can check car availability, prices, "
                f"financing, and book a test drive. What are you looking for?")

    if any(k in text for k in ["test drive", "test-drive"]):
        return ("I can set up a test drive. Tell me the car (or listing code, e.g. LT-014) and a "
                "preferred day, and I'll pass it straight to our sales team on WhatsApp.")

    if any(k in text for k in ["financing", "finance", "loan", "installment", "instalment", "credit"]):
        return ("We work with a few local partner banks and microfinance houses for auto loans, "
                "typically 20–30% down with terms up to 36 months. Share the car you're interested "
                "in and I'll have a sales rep send you the exact terms on WhatsApp.")

    if any(k in text for k in ["hour", "open", "close", "time"]):
        return f"We're open {BUSINESS_HOURS}. You're welcome to visit the showroom or chat here anytime."

    if any(k in text for k in ["where", "location", "address", "located"]):
        return f"Our showroom is in {BUSINESS_LOCATION}. Want directions or to book a visit?"

    if any(k in text for k in ["warranty", "guarantee"]):
        return ("Every vehicle is inspected before listing, and used cars come with a 30-day "
                "mechanical warranty; new vehicles carry the manufacturer warranty. Ask about a "
                "specific car and I'll confirm its exact coverage.")

    if any(k in text for k in ["trade", "trade-in", "sell my car", "sell my old"]):
        return ("We do accept trade-ins. Send us the make, model, year and mileage of your current "
                "car (a photo helps too) and our team will give you an estimate.")

    if any(k in text for k in ["human", "agent", "person", "call me", "speak to someone"]):
        return "Sure — I'll flag this for our sales team to reach out to you directly."

    cars = _matching_cars(message)
    if cars:
        formatted = _format_cars(cars)
        return f"Here's what we currently have that matches:\n{formatted}\n\nWant details or to book a test drive on any of these?"

    if any(k in text for k in ["price", "cost", "how much"]):
        return "Which car are you asking about? Share the make/model or listing code and I'll get you the exact price."

    if any(k in text for k in ["available", "in stock", "do you have"]):
        return "Tell me the make and model (or budget) you're after and I'll check current stock for you."

    return ("Got it — I've noted that for our sales team. In the meantime you can browse all "
            "current listings on the Cars page, or tell me a make, model, or budget and I'll "
            "search live inventory for you.")


def answer_customer_question(message, session_history=None):
    """Returns (reply_text, should_escalate_to_human: bool)."""
    if not message or not message.strip():
        return "Ask me about a car, price, financing, or booking a test drive.", False

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    escalate = any(k in message.lower() for k in ["human", "agent", "speak to someone", "call me"])

    if api_key:
        try:
            return _llm_reply(message, session_history, api_key), escalate
        except Exception:
            # Fall through to the rule engine if the API call fails for any reason —
            # the widget should never go silent on the customer.
            pass

    return _rule_based_reply(message, session_history), escalate


def _llm_reply(message, session_history, api_key):
    """Optional: route through Claude for more natural replies, grounded in live inventory."""
    import anthropic
    from app.models.car import CarListing
    from app.models.product import Product

    listings = (
        CarListing.query.join(Product)
        .filter(CarListing.is_published.is_(True), Product.is_active.is_(True), Product.stock_quantity > 0)
        .order_by(CarListing.created_at.desc())
        .limit(40)
        .all()
    )
    inventory_lines = "\n".join(
        f"- {c.listing_code}: {c.title}, {c.mileage_km:,}km, {c.transmission}, {c.condition}, "
        f"{c.price:,.0f} {os.environ.get('CURRENCY_SYMBOL', 'CFA')}"
        for c in listings
    ) or "No vehicles currently in stock."

    system_prompt = (
        f"You are the helpful sales assistant for {BUSINESS_NAME}, an online car dealership. "
        f"Business hours: {BUSINESS_HOURS}. Location: {BUSINESS_LOCATION}. "
        "Only recommend vehicles that appear in the CURRENT INVENTORY list below — never invent "
        "a car, price, or spec that isn't listed. Keep replies short (2-4 sentences), warm, and "
        "end with a clear next step (view listing, book a test drive, or chat on WhatsApp).\n\n"
        f"CURRENT INVENTORY:\n{inventory_lines}"
    )

    client = anthropic.Anthropic(api_key=api_key)
    messages = []
    for turn in (session_history or [])[-6:]:
        messages.append({"role": turn["role"], "content": turn["content"]})
    messages.append({"role": "user", "content": message})

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=400,
        system=system_prompt,
        messages=messages,
    )
    return "".join(block.text for block in response.content if getattr(block, "type", "") == "text").strip()
